title: "new title"

remote_theme: "mmistakes/so-simple-theme@3.2.0"
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


layout: page
title: "kaitlyn's writing portfolio"

permalink: /nine
permalink: /i-would-have-reached-out-further
permalink: /it-is-never-morning
permalink: /she-has-a-palace-down
permalink: /date
permalink: /the-willow-woman